site_name: UCUPAINT
site_description : Ucupaint is Blender addon to manage texture as layers for Eevee and Cycles renderer.
theme: 
  name : readthedocs
  icon:
    admonition:
      <type>: <icon>
nav:
  - Documentation :
    - Quick Setup : 01.00.quick-setup.md
    - Channel : 01.01.channel.md 
    - Layer : 01.02.layer.md
    - Layer Channel : 01.03.layer-channel.md
    - Mask : 01.04.mask.md
    - Modifier : 01.05.modifier.md
    - Preview Mode : 01.06.preview-mode.md
    - Bake to Layer : 01.07.bake-to-layer.md
    - Transfer UV : 01.08.transfer-uv.md
    - Bake Channels : 01.09.bake-channels.md
  - Resources :
    - File Examples : 01.10.resources.md
    - Video Tutorials : video-tutorials.md
    - Written Tutorials : text-tutorials.md
  - Tips & Troubleshooting :
    - Performance Tips: performance-tips.md
    - Pink Material: 01.11.extras.md
  - Development :
    - Roadmaps : roadmaps.md
    - Credits : 01.12.contributors.md
extra_css:
  - css/extra.css
plugins:
  - search
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "100%"           
        max-width: "800px"      
        height: "auto"         
        display: "block"
        margin: "auto"
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - tables
